import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
    return {
        rules: [
            {
                userAgent: '*',
                allow: '/',
                disallow: [
                    '/profile/*',
                    '/api/*',
                    "________",
                    'Lake Home answer:',
                    "Nightstand",
                    "Sofa",
                    "Book",
                    "Cabinet",
                    "Lamp",
                    "Fireplace",
                    "Window",
                    "Kitchen",
                    "Rug",
                    "Picture",
                    "________",
                    "Office answer:",
                    "A keyboard",
                    "The letter 'I'",
                    "A book",
                    "A notepad",
                    "A stapler",
                    "A stapler (paperclip)",
                    "A computer mouse",
                    "An eraser",
                    "A tape dispenser",
                    "A clock",
                    "________",
                    "Pent House answer:",
                    "A penthouse",
                    "A sofa",
                    "A chandelier",
                    "A dresser",
                    "A kitchen",
                    "A bookshelf",
                    "A bathtub",
                    "A lounge chair",
                    "A coffee table",
                    "A fireplace",
                    "________",
                    "Small Bedroom answer:",
                    "Pillow",
                    "Dresser",
                    "Mattress",
                    "Closet",
                    "Blanket",
                    "Alarm clock",
                    "Lamp",
                    "Nightstand",
                    "Pillow",
                    "Wardrobe",
                    "________",
                ],
            },
        ],
        sitemap: 'https://enigmaescape.vercel.app/sitemap.xml',
    }
}
